# Generated by Django 5.2.8 on 2026-02-06 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checklistitem',
            old_name='text',
            new_name='description',
        ),
    ]
