# Generated by Django 5.2.8 on 2026-02-18 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subtask',
            name='unique_order_per_task',
        ),
    ]
