# Generated by Django 5.2.8 on 2026-02-15 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_subtask_order_subtask_unique_order_per_task'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subtask',
            name='unique_order_per_task',
        ),
        migrations.AlterField(
            model_name='subtask',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
